version: '3'
services:
  face_aging_concept_drift:
    build: .
    container_name: face_aging_concept_drift
    tty: true
    ports:
      - "8081:8081"
    volumes:
      - .:/home/project
    networks:
      static-network:
        ipv4_address: 172.10.0.5
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.10.0.0/16
          #docker-compose v3+ do not use ip_range
          # ip_range: 192.168.0.1/24
