version: '3'
services:
  OpenVINO:
    build: ./Dockerfile.1
    container_name: OpenVINO
    tty: true
    ports:
      - "8082:8082"
    volumes:
      - .:/home/project
    networks:
      static-network:
        ipv4_address: 172.10.0.6
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.10.0.0/16
          #docker-compose v3+ do not use ip_range
          # ip_range: 192.168.0.1/24
